/**
 * Single source of truth for identity, URLs and contact details.
 * Facts here match the LinkedIn profile (Profile.pdf, Aug 2026).
 *
 * When the custom domain is live, change `url` and re-run `npm run build`:
 * meta tags, JSON-LD, robots.txt and sitemap.xml are all generated from it.
 */

export const SITE = {
  url: 'https://tufailakram-portfolio.netlify.app',
  name: 'Tufail Akram',
  role: 'Backend & AI Engineer',
  // 53 chars — fits Google's ~60-char display.
  title: 'Tufail Akram — Python Backend & AI Engineer, Hyderabad',
  // 157 chars.
  description:
    'Backend and AI engineer, 5+ years in Python, FastAPI and Django. I build REST APIs, Snowflake ETL and LLM/RAG systems at BayRock Labs, from Hyderabad, India.',
  locality: 'Hyderabad',
  region: 'Telangana',
  country: 'IN',
  countryName: 'India',
  timezone: 'IST (UTC+5:30)',
  email: 'tufailakram81@gmail.com',
  phone: '+91 70085 66127',
  phoneHref: 'tel:+917008566127',
  whatsapp: 'https://wa.me/917008566127',
  resume: '/Tufail-Akram-Resume.pdf',
  // Square avatar for the circular hero portrait, generated by scripts/make-images.py.
  avatar: '/tufail-avatar.jpg',
  avatarSize: 512,
  avatarWebpSrcset: '/tufail-avatar-256.webp 256w, /tufail-avatar.webp 512w',
  avatarSizes: '(min-width: 768px) 256px, 208px',
  ogImage: '/og.png',
  themeColor: '#121110',
  // Update both when the content changes: footer line, then sitemap <lastmod>.
  lastUpdated: 'August 2026',
  lastmod: '2026-08-17',
} as const;

export const SOCIALS = [
  { label: 'GitHub', handle: 'akram1089', href: 'https://github.com/akram1089' },
  { label: 'LinkedIn', handle: 'tufail-akram', href: 'https://www.linkedin.com/in/tufail-akram' },
  { label: 'X', handle: '@tufailakram1089', href: 'https://x.com/tufailakram1089' },
] as const;

/** Order drives the dock, the scroll-spy and the footer links. */
export const SECTIONS = [
  { id: 'home', label: 'Home', icon: 'home' },
  { id: 'about', label: 'About', icon: 'user' },
  { id: 'skills', label: 'Skills', icon: 'code' },
  { id: 'experience', label: 'Experience', icon: 'briefcase' },
  { id: 'projects', label: 'Projects', icon: 'folder' },
  { id: 'contact', label: 'Contact', icon: 'mail' },
] as const;
